var N = null;var sourcesIndex = {};
sourcesIndex["aero"] = {"name":"","dirs":[{"name":"drivers","files":["keyboard.rs","mod.rs","mouse.rs"]},{"name":"gdt","files":["gdt.rs","mod.rs"]},{"name":"interrupts","files":["exceptions.rs","idt.rs","irq.rs","mod.rs"]},{"name":"memory","files":["alloc.rs","mod.rs","paging.rs"]},{"name":"utils","files":["io.rs","memory.rs","mod.rs"]},{"name":"vga","files":["buffer.rs","color.rs","mod.rs","rendy.rs"]}],"files":["main.rs","panic.rs","pit.rs","tests.rs"]};
sourcesIndex["bit_field"] = {"name":"","files":["lib.rs"]};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["bootloader"] = {"name":"","dirs":[{"name":"bootinfo","files":["memory_map.rs","mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["core_lazy.rs","lib.rs"]};
sourcesIndex["lock_api"] = {"name":"","files":["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]};
sourcesIndex["scopeguard"] = {"name":"","files":["lib.rs"]};
sourcesIndex["spin"] = {"name":"","dirs":[{"name":"mutex","files":["spin.rs"]}],"files":["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]};
sourcesIndex["volatile"] = {"name":"","files":["lib.rs"]};
sourcesIndex["x86_64"] = {"name":"","dirs":[{"name":"instructions","files":["interrupts.rs","mod.rs","port.rs","random.rs","segmentation.rs","tables.rs","tlb.rs"]},{"name":"registers","files":["control.rs","mod.rs","model_specific.rs","rflags.rs"]},{"name":"structures","dirs":[{"name":"paging","dirs":[{"name":"mapper","files":["mapped_page_table.rs","mod.rs","offset_page_table.rs","recursive_page_table.rs"]}],"files":["frame.rs","frame_alloc.rs","mod.rs","page.rs","page_table.rs"]}],"files":["gdt.rs","idt.rs","mod.rs","port.rs","tss.rs"]}],"files":["addr.rs","lib.rs"]};
createSourceSidebar();
