var N = null;var sourcesIndex = {};
sourcesIndex["aero_boot"] = {"name":"","files":["lib.rs"]};
sourcesIndex["aero_kernel"] = {"name":"","dirs":[{"name":"acpi","files":["fadt.rs","hpet.rs","madt.rs","mcfg.rs","mod.rs","rsdp.rs","sdt.rs"]},{"name":"arch","dirs":[{"name":"x86_64","dirs":[{"name":"interrupts","files":["exceptions.rs","idt.rs","irq.rs","mod.rs"]},{"name":"memory","files":["alloc.rs","mod.rs","paging.rs"]}],"files":["cpu.rs","gdt.rs","mod.rs"]}],"files":["mod.rs"]},{"name":"drivers","files":["ahci.rs","keyboard.rs","mod.rs","mouse.rs","pci.rs"]},{"name":"syscall","files":["fs.rs","mod.rs","time.rs"]},{"name":"userland","files":["elf.rs","mod.rs","process.rs","scheduler.rs"]},{"name":"utils","files":["io.rs","memory.rs","mod.rs"]},{"name":"vga","files":["color.rs","mod.rs","rendy.rs"]}],"files":["logger.rs","main.rs","panic.rs","tests.rs","time.rs"]};
sourcesIndex["bit_field"] = {"name":"","files":["lib.rs"]};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["bootloader"] = {"name":"","files":["boot_info.rs","config.rs","lib.rs"]};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["font8x8"] = {"name":"","files":["basic.rs","block.rs","box.rs","greek.rs","hiragana.rs","latin.rs","legacy.rs","lib.rs","misc.rs","sga.rs","unicode.rs"]};
sourcesIndex["goblin"] = {"name":"","dirs":[{"name":"elf","files":["compression_header.rs","constants_header.rs","constants_relocation.rs","dynamic.rs","gnu_hash.rs","header.rs","mod.rs","note.rs","program_header.rs","reloc.rs","section_header.rs","sym.rs"]}],"files":["lib.rs","strtab.rs"]};
sourcesIndex["lazy_static"] = {"name":"","files":["core_lazy.rs","lib.rs"]};
sourcesIndex["linked_list_allocator"] = {"name":"","files":["hole.rs","lib.rs"]};
sourcesIndex["lock_api"] = {"name":"","files":["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]};
sourcesIndex["log"] = {"name":"","files":["lib.rs","macros.rs"]};
sourcesIndex["plain"] = {"name":"","files":["error.rs","lib.rs","methods.rs","plain.rs"]};
sourcesIndex["scopeguard"] = {"name":"","files":["lib.rs"]};
sourcesIndex["scroll"] = {"name":"","files":["ctx.rs","endian.rs","error.rs","greater.rs","leb128.rs","lib.rs","pread.rs","pwrite.rs"]};
sourcesIndex["spin"] = {"name":"","dirs":[{"name":"mutex","files":["spin.rs"]}],"files":["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]};
sourcesIndex["spinning_top"] = {"name":"","files":["lib.rs","spinlock.rs"]};
sourcesIndex["static_assertions"] = {"name":"","files":["assert_cfg.rs","assert_eq_align.rs","assert_eq_size.rs","assert_fields.rs","assert_impl.rs","assert_obj_safe.rs","assert_trait.rs","assert_type.rs","const_assert.rs","lib.rs"]};
sourcesIndex["ucs2"] = {"name":"","files":["lib.rs"]};
sourcesIndex["uefi"] = {"name":"","dirs":[{"name":"data_types","files":["chars.rs","enums.rs","guid.rs","mod.rs","strs.rs"]},{"name":"proto","dirs":[{"name":"console","dirs":[{"name":"pointer","files":["mod.rs"]},{"name":"text","files":["input.rs","mod.rs","output.rs"]}],"files":["gop.rs","mod.rs","serial.rs"]},{"name":"debug","files":["mod.rs"]},{"name":"loaded_image","files":["device_path.rs","mod.rs"]},{"name":"media","dirs":[{"name":"file","files":["dir.rs","info.rs","mod.rs","regular.rs"]}],"files":["fs.rs","mod.rs"]},{"name":"pi","files":["mod.rs","mp.rs"]}],"files":["mod.rs"]},{"name":"result","files":["completion.rs","error.rs","mod.rs","status.rs"]},{"name":"table","files":["boot.rs","cfg.rs","header.rs","mod.rs","revision.rs","runtime.rs","system.rs"]}],"files":["lib.rs","prelude.rs"]};
sourcesIndex["volatile"] = {"name":"","files":["access.rs","lib.rs"]};
sourcesIndex["x86_64"] = {"name":"","dirs":[{"name":"instructions","files":["interrupts.rs","mod.rs","port.rs","random.rs","segmentation.rs","tables.rs","tlb.rs"]},{"name":"registers","files":["control.rs","mod.rs","model_specific.rs","rflags.rs","xcontrol.rs"]},{"name":"structures","dirs":[{"name":"paging","dirs":[{"name":"mapper","files":["mapped_page_table.rs","mod.rs","offset_page_table.rs","recursive_page_table.rs"]}],"files":["frame.rs","frame_alloc.rs","mod.rs","page.rs","page_table.rs"]}],"files":["gdt.rs","idt.rs","mod.rs","port.rs","tss.rs"]}],"files":["addr.rs","lib.rs"]};
createSourceSidebar();
